name: Deploy on GH Pages

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v6
      with:
        persist-credentials: false
    - uses: actions/setup-node@v6
      with:
        cache: npm
        node-version-file: .nvmrc
    - run: npm install
    - run: npm install --global rollup@2.79.1
    - run: export BASEPATH='/WAI/eval/report-tool' && npm run clean:build && rollup -c
    - run: cd build && ln -s index.html 404.html # symlink for GH pages fallback
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        BRANCH: gh-pages
        FOLDER: build
    - name: Create zip file 🗂
      uses: vimtor/action-zip@v1.3
      with:
        files: build/
        dest: result.zip 
